### ISSUE TITLE
Loadout / Set

### ISSUE THREAD

**Issue by SilenceM59** [SilenceM59/meridian59.net#6]
Go.

**Comment by NiNjAz** [comment]
1.  Set:  cast set / use set scroll to save the contents of your inventory into a memory

2.  Loadout: cast loadout / use loadout scroll to pull the items/regs from your guildhall to match the memorized content of your inventory.

* loadout will only pull items/regs that are missing from the memorized inventory.

I.E. if u had 50 purple mushrooms when u cast set, 45 when you cast loadout, 5 purple mushrooms will be pulled from the guildhall (obviously the contents need to be in the hall, so a little chest maintenance is required)

**Comment by SilenceM59** [comment]
@NiNjAz Let's say that Loadout/Set already works as you explained (or if it doesn't I will need to get it from 103?) -- on top of its `expected behavior`, is there anything else that could use improvement?

**Comment by NiNjAz** [comment]
Set & Loadout work the same on all servers.  What's different is convey.  On 103 theres a 2nd convey spell called guild convey that allows you to convey regs from your inventory  to guildhall  (normal convey sends to vaults).  Also, on 103 set and loadout come in spell form as well.  

If i can think of any ways to imorove it ill post.

**Comment by SilenceM59** [comment]
+1 on guild convey.

I will hopefully be able to snag that from 103's repository and add it in. If not, I can manufacture one using code from the Set/Loadout code which interacts with the guild hall chest.

**Comment by SilenceM59** [comment]
@NiNjAz Let me know if I can close this out.

Check 115 for Guild Convey, Loadout and Set spells.

All tested.

**Comment by SilenceM59** [comment]
@NiNjAz Closing this issue. Check 115 - Let me know if things are working to your expectations, everything seems to work great for me.
